apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rku4e83ie-nodejs
  janus-idp.io/tekton: rku4e83ie-nodejs
  backstage.io/kubernetes-id: rku4e83ie-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rku4e83ie-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
