apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rku4e83ie-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rku4e83ie-nodejs 
  name: rku4e83ie-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rku4e83ie-nodejs 
